spring:
  application:
    name: notification-service

  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      username: ${CONFIG_SERVER_USER:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}
      fail-fast: false

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/smartorder_notifications}

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest

  mail:
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eurekauser:eurekapass@localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.smartorder.notification: DEBUG
    org.springframework.kafka: INFO